### ISSUE TITLE
Unchanged description metadata

### ISSUE THREAD

**Issue by KOliver94** [simonyiszk/simonyi-web#12]
In the [index.html](https://github.com/simonyiszk/simonyi-web/blob/fcb816a/public/index.html) file the following part was left unchanged:
```html
<meta
   name="description"
   content="Web site created using create-react-app"
 />
```

For this reason eg. on [Facebook](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fsimonyi.bme.hu%2F) when the site is shared the preview looks like this:
![2020-04-16 20_13_54-Messenger](https://user-images.githubusercontent.com/19346498/79491514-dd655000-801e-11ea-8c7e-3576e143612a.png)

Moreover, it might be worth considering to add an image metadata which can be used for sharing.

**Comment by kripod** [comment]
The description can be changed by editing [`public/index.html`](https://github.com/simonyiszk/simonyi-web/blob/fcb816a5895c97d2710d46a89b3181768fe0fd09/public/index.html#L26). A social media cover can also be added right there, with the following `<meta>` tag:

```html
<meta property="og:image" content="https://simonyi.bme.hu/cover.png" />
```

Please be aware that [Open Graph](https://ogp.me/) tags use absolute URLs to represent objects. I recommend using an 1200x630px PNG file compressed with [`pingo -s9 cover.png`](https://css-ig.net/pingo), placed at `public/cover.png`. Make sure to use safe margins as seen in GitHub's recommended social preview template:

![repository-open-graph-template](https://user-images.githubusercontent.com/14854048/79493715-2c60b480-8022-11ea-8201-533289ab86e4.png)

_(Note that GitHub uses an unconventional resolution for social media previews.)_

**Comment by kripod** [comment]
@KOliver94 If you would like to work on a pull request, please assign this issue to yourself. Don't forget to link the PR to this issue [with a magic keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when done. (So the issue will get auto-closed once resolved.)
